// Generates src/changes.ts from CHANGELOG.md — the runtime source for the /changes command.
// CLI code can't read CHANGELOG.md at runtime (it isn't packaged in `files`), so we materialize
// the most recent entries as an in-tree module. Runs via the `prebuild` hook; release.yml rebuilds
// after writing CHANGELOG, so a fresh publish always ships current notes. Writes only on change.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const changelog = join(root, "CHANGELOG.md");
const RECENT = 10;

// Each release is "## vX.Y.Z — DATE" then a blank line then one or more paragraphs (a release that
// bundles several changesets has one paragraph each). Capture the version, date, and EVERY paragraph
// — `summaries` is the full list, `summary` is the first (kept for single-line callers). Capturing
// only the first paragraph would hide every change after the first in a bundled release (e.g. the
// headline feature buried under a release-plumbing fix), so the TUI must see them all.
const text = existsSync(changelog) ? readFileSync(changelog, "utf8") : "";
const entries = [];
for (const block of text.split(/^## v/m).slice(1)) {
  const m = block.match(/^(\d+\.\d+\.\d+) — (\S+)\n+([\s\S]*)$/);
  if (!m) continue;
  const summaries = m[3]
    .split(/\n\s*\n/)               // paragraphs are blank-line separated
    .map((p) => p.replace(/\s+/g, " ").trim())
    .filter(Boolean);
  if (!summaries.length) continue;
  entries.push({ version: m[1], date: m[2], summary: summaries[0], summaries });
  if (entries.length >= RECENT) break;
}

const out =
  `// AUTO-GENERATED by scripts/gen-changes.mjs from CHANGELOG.md — do not edit.\n` +
  `export interface ChangeEntry { version: string; date: string; summary: string; summaries: string[] }\n` +
  `export const APP_CHANGES: ChangeEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

const target = join(root, "src", "changes.ts");
if (!existsSync(target) || readFileSync(target, "utf8") !== out) {
  writeFileSync(target, out);
  console.log(`gen-changes: wrote src/changes.ts (${entries.length} entries)`);
} else {
  console.log(`gen-changes: src/changes.ts already up to date (${entries.length} entries)`);
}
