// Generates src/changes.ts from CHANGELOG.md — the runtime source for the /changes command.
// CLI code can't read CHANGELOG.md at runtime (it isn't packaged in `files`), so we materialize
// the most recent entries as an in-tree module. Runs via the `prebuild` hook; release.yml rebuilds
// after writing CHANGELOG, so a fresh publish always ships current notes. Writes only on change.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const changelog = join(root, "CHANGELOG.md");
const RECENT = 10;

// Each release is "## vX.Y.Z — DATE" then a blank line then a one-paragraph summary. Capture the
// version, date, and summary so the TUI can list recent entries without bundling the whole file.
const text = existsSync(changelog) ? readFileSync(changelog, "utf8") : "";
const entries = [];
const re = /^## v(\d+\.\d+\.\d+) — (\S+)\n+([^\n]+)/gm;
for (let m = re.exec(text); m && entries.length < RECENT; m = re.exec(text)) {
  entries.push({ version: m[1], date: m[2], summary: m[3].trim() });
}

const out =
  `// AUTO-GENERATED by scripts/gen-changes.mjs from CHANGELOG.md — do not edit.\n` +
  `export interface ChangeEntry { version: string; date: string; summary: string }\n` +
  `export const APP_CHANGES: ChangeEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

const target = join(root, "src", "changes.ts");
if (!existsSync(target) || readFileSync(target, "utf8") !== out) {
  writeFileSync(target, out);
  console.log(`gen-changes: wrote src/changes.ts (${entries.length} entries)`);
} else {
  console.log(`gen-changes: src/changes.ts already up to date (${entries.length} entries)`);
}
