// Generates src/version.ts from package.json — the single source of truth for the app version.
// Run automatically via the `prebuild` npm hook, and by the release workflow after bumping.
// CLI code can't `import "../package.json"` because rootDir is "src" (it's outside), so we
// materialize the version as an in-tree module instead. Writes only when the content changes,
// so repeated builds don't churn git.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;
const out = `// AUTO-GENERATED by scripts/gen-version.mjs from package.json — do not edit.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`;

const target = join(root, "src", "version.ts");
if (!existsSync(target) || readFileSync(target, "utf8") !== out) {
  writeFileSync(target, out);
  console.log(`gen-version: wrote src/version.ts (APP_VERSION=${version})`);
} else {
  console.log(`gen-version: src/version.ts already up to date (APP_VERSION=${version})`);
}
