// AUTO-GENERATED by scripts/gen-changes.mjs from CHANGELOG.md — do not edit.
export interface ChangeEntry { version: string; date: string; summary: string; summaries: string[] }
export const APP_CHANGES: ChangeEntry[] = [
  {
    "version": "0.14.2",
    "date": "2026-07-02",
    "summary": "chore(package): drop README images from the npm tarball (reference them via GitHub raw URLs) — shrinks the published package from 288 kB to 67 kB",
    "summaries": [
      "chore(package): drop README images from the npm tarball (reference them via GitHub raw URLs) — shrinks the published package from 288 kB to 67 kB"
    ]
  },
  {
    "version": "0.14.1",
    "date": "2026-07-01",
    "summary": "fix(worker): only route to Copilot's Responses API when a model advertises it, and only send `reasoning_effort` to models that support it.",
    "summaries": [
      "fix(worker): only route to Copilot's Responses API when a model advertises it, and only send `reasoning_effort` to models that support it.",
      "Two related upstream-routing bugs, both surfaced by the real-CLI e2e:",
      "1. **Responses mis-routing.** A `/chat` 400 whose body matched the responses-only hint regex (`does not support …`, `invalid_request_body`) tripped the safety net into retrying on `/responses` — which is gpt-5-class only. For a Claude *or* gpt-4o turn that retry then 400'd (\"model X does not support / is not supported via Responses API\"), masking the real `/chat` error. The `/responses` route (primary and both 400 safety nets) is now gated on the live endpoint map positively listing `/responses` for the model, so only gpt-5.x / mai-code ever go there; every other model surfaces its true `/chat` failure.",
      "2. **`reasoning_effort` sent to models that reject it.** `claude -p` defaults to gpt-4o and sends `effort=high`, but gpt-4o doesn't advertise `reasoning_effort` → every turn 400'd (`invalid_reasoning_effort`) — previously hidden behind bug 1. The adapter now gates the `/chat` `reasoning_effort` field on the model's advertised capability (from `/models`), defaulting to \"send\" only until discovery resolves so a supported model's reasoning turn is never silently dropped."
    ]
  },
  {
    "version": "0.14.0",
    "date": "2026-07-01",
    "summary": "Downscale oversized images before they reach Copilot, fixing `model_max_prompt_tokens_exceeded` (a 502 relayed to the client) when a large image is in play. Copilot's `/chat` has no vision tiler for Claude models — it bills an inline `data:...;base64,...` URL as plain text at ~char/4, so a single full-resolution image (~9MB base64 ≈ 2.3M tokens) overflows the model's prompt limit. The worker now takes over the job the real Anthropic backend does for us: decode → downscale → re-encode as JPEG, collapsing the payload before send.",
    "summaries": [
      "Downscale oversized images before they reach Copilot, fixing `model_max_prompt_tokens_exceeded` (a 502 relayed to the client) when a large image is in play. Copilot's `/chat` has no vision tiler for Claude models — it bills an inline `data:...;base64,...` URL as plain text at ~char/4, so a single full-resolution image (~9MB base64 ≈ 2.3M tokens) overflows the model's prompt limit. The worker now takes over the job the real Anthropic backend does for us: decode → downscale → re-encode as JPEG, collapsing the payload before send.",
      "The gate and the target are **bytes, not pixels** — because base64 length is exactly what Copilot bills. Images already under a per-image byte budget (~1.5MB) are forwarded byte-identical without even decoding (so small images cost nothing), and an over-budget image is downscaled to a 1568px edge AND stepped down through a JPEG quality/resolution ladder until the encoded result actually fits the budget. This closes the gap a pixel-only gate leaves open: a high-detail photo whose long edge is already within the cap but whose bytes are huge (the \"I read a normal-looking image and still got a 502\" case) is now shrunk too.",
      "Crucially this covers images returned **inside a `tool_result`** (a Bash command or MCP tool that emits a screenshot) — the real-world trigger, where the image was previously flattened into the tool result's text string and so bypassed both resize and token counting entirely. `tool_result` now carries structured images end-to-end: preserved on the Anthropic/OpenAI inbound paths, downscaled + counted, and forwarded inline on the Copilot `tool` message (which Copilot accepts — probed). The Responses path, whose `function_call_output` can't carry an image, notes the omission instead of shipping raw base64.",
      "Runs on every image path (`/anthropic/v1/messages`, `/openai/chat/completions`, `/openai/responses`) and in `count_tokens`, so Claude Code's context sizing and the actual request agree. `estimateTokens` also now counts image bytes at all (top-level and inside tool results); it previously ignored images, under-reporting by millions and letting the client ship an oversized prompt straight into the 502.",
      "Performance is bounded: a text-only request costs ~0.04ms and an under-budget image ~0.002ms (byte short-circuit, no decode), so normal traffic is unaffected. A persistent oversized image in history — re-sent every turn, and hit by both `count_tokens` and `messages` — is decoded and re-encoded only ONCE: results are cached by content (LRU), turning a ~2s/turn cost into a first-turn-only cost (measured ~4.3s cold → ~45ms warm)."
    ]
  },
  {
    "version": "0.13.0",
    "date": "2026-06-30",
    "summary": "feat(reasoning): extended thinking + reasoning-effort passthrough. A `thinking`-enabled Anthropic request (or an OpenAI `reasoning_effort`) now drives the model's reasoning, and the chain-of-thought streams back as a native Anthropic thinking block (thinking_delta + signature_delta) ahead of the answer — so Claude Code renders its thinking panel through the proxy. The signed continuation token (reasoning_opaque) round-trips across tool-call turns to preserve reasoning context. Effort is also forwarded on the /responses path for gpt-5 models. Verified end-to-end against live Copilot.",
    "summaries": [
      "feat(reasoning): extended thinking + reasoning-effort passthrough. A `thinking`-enabled Anthropic request (or an OpenAI `reasoning_effort`) now drives the model's reasoning, and the chain-of-thought streams back as a native Anthropic thinking block (thinking_delta + signature_delta) ahead of the answer — so Claude Code renders its thinking panel through the proxy. The signed continuation token (reasoning_opaque) round-trips across tool-call turns to preserve reasoning context. Effort is also forwarded on the /responses path for gpt-5 models. Verified end-to-end against live Copilot."
    ]
  },
  {
    "version": "0.12.0",
    "date": "2026-06-30",
    "summary": "feat(tui): LAN switch now shows paste-ready remote client config (Claude + Codex)",
    "summaries": [
      "feat(tui): LAN switch now shows paste-ready remote client config (Claude + Codex)",
      "Switching `/network` to LAN used to dump the URL + key and a one-line \"send it as `Authorization: Bearer`\" hint, leaving the user to hand-assemble each remote machine's config and guess which slot the key goes in. The LAN success card now renders **paste-ready config blocks** for both clients, with the key already in the correct place:",
      "- **Claude** → `~/.claude/settings.json` `env` block (key in `ANTHROPIC_API_KEY`) - **Codex** → `~/.codex/config.toml` provider block (key in `experimental_bearer_token`)",
      "Blocks are built by a new pure helper (`tui/setup/remote-config.ts`) that reuses the same `claudeCopilotReverseEnv` / codex-toml shape local `/setup` writes, so a remote config matches what local setup produces — only the LAN host + real key replace loopback + the local placeholder. Each block uses the model this machine has pinned for that client (falling back to sensible defaults) and its real context window when known (Claude `CLAUDE_CODE_AUTO_COMPACT_WINDOW`, Codex `model_context_window`), so the remote client sizes context like the local one instead of assuming a default ~200K window for a 1M model. If the LAN IPv4 can't be determined, the card falls back to a `<this-machine-LAN-IP>` placeholder instead of crashing."
    ]
  },
  {
    "version": "0.11.1",
    "date": "2026-06-30",
    "summary": "fix(worker,supervisor): stop three recurring 502/crash failures behind `/doctor` and the daemon",
    "summaries": [
      "fix(worker,supervisor): stop three recurring 502/crash failures behind `/doctor` and the daemon",
      "- **EADDRINUSE crash loop → daemon \"unhealthy\"**: a forked worker no longer orphans when its supervisor dies abnormally (terminal closed/killed/crashed). The worker now exits on IPC `disconnect`, releasing `:7891` instead of squatting it so the next supervisor's worker can't bind. The supervisor's manual restart also waits for the old worker to fully exit before spawning the replacement, closing the kill/respawn race that hit the same `listen EADDRINUSE :7891`. - **502 `Cannot read properties of undefined (reading 'message')`**: the Copilot adapter's non-stream `complete()` guards an empty `choices` array (a content-filtered turn or a 1-token ping) and returns an empty completion instead of throwing. - **502 `Invalid 'max_output_tokens'` on responses-only models (e.g. gpt-5.5)**: `max_output_tokens` is clamped up to the Responses API minimum of 16, so `/doctor`'s 1-token ping (and Claude Code's connection probe) no longer 400s.",
      "Docker HTTP e2e gains an EADDRINUSE regression block (orphaned worker releases its port when the IPC parent drops; daemon stays `ready` through restart churn); new units cover the empty-choices guard, the `max_output_tokens` floor, and the restart-waits-for-exit ordering."
    ]
  },
  {
    "version": "0.11.0",
    "date": "2026-06-30",
    "summary": "fix(tui): `/logs` and `/metrics` no longer shatter their bordered card when an upstream error carries newlines (a Copilot 502 returns a whole HTML page). Errors are flattened to a single line at the source (`errorDetail`) and again where the commands render them, and `OutputCard` now splits any multiline content into separate rows as a final backstop.",
    "summaries": [
      "fix(tui): `/logs` and `/metrics` no longer shatter their bordered card when an upstream error carries newlines (a Copilot 502 returns a whole HTML page). Errors are flattened to a single line at the source (`errorDetail`) and again where the commands render them, and `OutputCard` now splits any multiline content into separate rows as a final backstop.",
      "feat(doctor+dashboard): `/doctor` is now a real self-check and the web dashboard shows current data. `/doctor` reports GitHub login, worker liveness, the resolved web-search backend (copilot/webiq/unavailable), model discovery, and — on the on-demand TUI run — a per-configured-model connectivity ping (one real 1-token request per model the clients are actually set to use). The 2s dashboard poll uses the cheap upstream-free checks (`/api/doctor` without `?ping`), so it never burns quota. The dashboard is redesigned for parity with the TUI: it counts a runaway-tagged 200 as an error (shared `isError` rule, not just `status>=400`), and adds GitHub login, web-search backend, advertised models (with `[1m]` badges), and per-scope Claude/Codex client config panels via new `/api/clients` and `/api/models` endpoints.",
      "fix(tui): `/metrics` now shows real totals instead of capping at the last 100 requests. The card aggregated a 100-row fetch, so once you crossed 100 requests it always read \"100 reqs\" and every derived number (errors, tokens, est. cost, per-model) was bounded to a meaningless sliding window. Metrics are now computed in SQL over the whole `request_log` via a new `/api/metrics` endpoint, and the card shows both **all-time** and **last 24h** rollups. As a bonus, `/logs`, `/report`, and the built-in assistant's `metrics`/`recent_errors` tools now read errors from a dedicated SQL query over the full table, so a failure that scrolled past the last-100-requests window still shows up.",
      "The browser **dashboard** (served at `/` on :7890) had the same bug on its own surface: it derived totals from the capped `/api/requests` fetch, so it stuck at \"total 100\", and its \"Recent requests\" panel was a flat dump of the last 30 rows (for a healthy proxy, 30 identical `200`s — no signal). The dashboard now renders the `/api/metrics` SQL rollup: real **all-time + last 24h** totals and a **per-model breakdown** (reqs / errors / avg ms / tokens) replacing the flat dump. Recent errors come from the full-table SQL query, so failures past the last-100 window show here too.",
      "Finally, a consistency pass across every surface that renders these metrics (the `/metrics` card, the `/metrics` + `/logs` slash commands, the dashboard, and the assistant's `metrics`/`recent_errors` tools): token-count and cost formatting are now a single shared `fmtTokens`/`fmtCost` (the assistant tool previously printed raw `39602000↑ $649.870` instead of `39602.0k↑ $649.87`), the assistant's `recent_errors` now flattens multi-line upstream bodies through `oneLine()` like the other surfaces, and the \"no errors\" empty state reads the same (`everything's green ✓`) everywhere.",
      "Also fixes the **`/metrics` card flicker**: the 2s status poll re-read the config files and called `setStatus` with a fresh object every tick, which defeated React's bail-out and repainted the whole frame — and when the tall metrics card overflowed the terminal, Ink repainted with a full clear, so the card visibly flickered every 2 seconds even when nothing changed. The poll now compares the freshly-read status by value (`sameStatus`) and keeps the previous object when it's unchanged, so an idle tick produces zero re-renders. The worker/GitHub badges still update live on a real change."
    ]
  },
  {
    "version": "0.10.1",
    "date": "2026-06-30",
    "summary": "fix(tui): the \"what's new\" banner now shows **one line per recent version**, each surfacing that version's main change — instead of flattening all changes from the newest version (which let a single bundled release fill every slot). For a version that bundled several changesets it picks the headline change (a `feat`/`perf`, or hand-written prose, over a `fix`/`chore`; ties broken by length), so e.g. v0.9.0 shows the network access-modes feature rather than the release-plumbing fix.",
    "summaries": [
      "fix(tui): the \"what's new\" banner now shows **one line per recent version**, each surfacing that version's main change — instead of flattening all changes from the newest version (which let a single bundled release fill every slot). For a version that bundled several changesets it picks the headline change (a `feat`/`perf`, or hand-written prose, over a `fix`/`chore`; ties broken by length), so e.g. v0.9.0 shows the network access-modes feature rather than the release-plumbing fix."
    ]
  },
  {
    "version": "0.10.0",
    "date": "2026-06-30",
    "summary": "feat(tui): the startup \"what's new\" banner now shows the real recent headlines (top 3 across recent releases, version-tagged) instead of a generic \"type /changes\" pointer — so a freshly shipped feature is actually visible on launch rather than the banner looking empty. `/changes` now lists every change in a bundled release: `gen-changes` captures all paragraphs of each release (not just the first), so a headline feature merged alongside a plumbing fix is no longer hidden. Each release renders as a header with one bullet per change.",
    "summaries": [
      "feat(tui): the startup \"what's new\" banner now shows the real recent headlines (top 3 across recent releases, version-tagged) instead of a generic \"type /changes\" pointer — so a freshly shipped feature is actually visible on launch rather than the banner looking empty. `/changes` now lists every change in a bundled release: `gen-changes` captures all paragraphs of each release (not just the first), so a headline feature merged alongside a plumbing fix is no longer hidden. Each release renders as a header with one bullet per change."
    ]
  },
  {
    "version": "0.9.0",
    "date": "2026-06-30",
    "summary": "fix(release): update CHANGELOG before the build so the just-released version appears in `/changes`. gen-changes.mjs runs in prebuild and reads CHANGELOG, but the workflow appended the new entry only after publish — so each release's own notes lagged one version behind. CHANGELOG is now written before build; changesets are still consumed after publish.",
    "summaries": [
      "fix(release): update CHANGELOG before the build so the just-released version appears in `/changes`. gen-changes.mjs runs in prebuild and reads CHANGELOG, but the workflow appended the new entry only after publish — so each release's own notes lagged one version behind. CHANGELOG is now written before build; changesets are still consumed after publish.",
      "feat(tui): `/metrics` now renders a styled card — a colored summary row (reqs · errors · tokens↑↓ · est. cost) over an aligned per-model table — instead of flat gray lines. Numbers carry accent/state colors, labels are dimmed, models sort by request count.",
      "feat(network): explicit access modes — **localhost** (default, loopback only — private to this machine) vs **LAN** (`/network` to enable). LAN exposes the worker proxy on the network and requires a key on every request **from another machine** — `Authorization: Bearer <key>` or `x-api-key` — rejecting a remote request without it (`401`) before any upstream call. Your own machine keeps working over `127.0.0.1` with no key, so local Claude/Codex need no change when you flip to LAN (the local-vs-remote decision is TCP-layer only, never a spoofable header). It's **fail-closed**: enabling LAN auto-generates a key (no keyless LAN), and a remote request is refused (`503`) if a key ever goes missing — never an open relay. The key (timing-safe compare) is read per request, so rotation needs no restart; flipping the mode restarts the worker to rebind the socket. The supervisor control plane stays on localhost regardless. New `/network` panel, a `/config` row, and a `net` HUD indicator."
    ]
  }
];
